image: docker:stable
stages:
  - test
  - deploy

services:
  - docker:dind

variables:
  GIT_SUBMODULE_STRATEGY: recursive

before_script:
  - apk update && apk add bash curl

latest:
  stage: test
  script:
    - ./kickstart.sh --ci-build
  only:
    - master

stable:
  stage: deploy
  script:
    - ./kickstart.sh --ci-build
    - echo "call curl deploy script here"
  when: on_success
  only:
    - tags
